import { Ambulance, Bell, CaretDown, FirstAid, Heartbeat, House, SignOut, Stethoscope, UserCircle, Users, WifiHigh } from "@phosphor-icons/react";
import { NavLink, Outlet, useLocation, useNavigate } from "react-router-dom";
import { useAuth, useCareGrid } from "../app/providers.jsx";
import { DEMO_MODE } from "../config.js";
import { PanicBanner } from "../components/alerts/PanicBanner.jsx";
import { SystemStatusDrawer } from "../components/common/SystemStatusDrawer.jsx";

const nav={ambulance:[["dashboard","Command",House],["emergency","Start Emergency",FirstAid],["patient","Patient",UserCircle],["hospital-finder","Hospital Finder",Heartbeat],["pre-alert","Pre-Alert",Bell],["history","History",Ambulance]],nurse:[["dashboard","Live Ward",House],["wards","Wards",Heartbeat],["beds","Beds",FirstAid],["patients","Patients",Users],["rfid","RFID",WifiHigh],["medications","Medications",Stethoscope],["pharmacy","Pharmacy",Heartbeat],["tasks","Tasks",Bell],["alerts","Alerts",Bell]],doctor:[["dashboard","Clinical Command",House],["emergencies","Emergencies",FirstAid],["patients","Patients",Users],["prescriptions","Prescriptions",Stethoscope],["orders","Orders",Heartbeat],["ambulances","Ambulances",Ambulance],["beds","Beds",FirstAid],["pharmacy","Pharmacy",Heartbeat],["reports","Reports",Bell]]};
const titles={ambulance:"Ambulance Driver",nurse:"Nurse Operations",doctor:"Doctor Portal"};
const connectionLabel={live:"LIVE",reconnecting:"RECONNECTING",offline:"OFFLINE",loading:"RECONNECTING"};

export function RoleLayout({role}){
  const {session,logout,switchRole}=useAuth(),{live,alerts,setSystemOpen}=useCareGrid(),navigate=useNavigate(),location=useLocation(),connection=live.connectionState||"offline";
  const signOut=async()=>{await logout();navigate("/login")};
  return <div className={`cg-shell role-${role}`}><aside className="cg-sidebar"><div className="cg-brand"><span><Heartbeat weight="fill"/></span><div><b>CareGrid</b><small>Smart Hospital Command Network</small></div></div><div className="cg-role-label"><span>{role==="ambulance"?<Ambulance/>:role==="nurse"?<FirstAid/>:<Stethoscope/>}</span><div><b>{titles[role]}</b><small>{session?.name}</small></div></div><nav>{nav[role].map(([path,label,Icon])=><NavLink key={path} to={`/${role}/${path}`} className={({isActive})=>isActive?"active":""}><Icon weight="duotone"/><span>{label}</span>{label==="Alerts"&&alerts.filter(a=>!a.acknowledged).length>0&&<em>{alerts.filter(a=>!a.acknowledged).length}</em>}</NavLink>)}</nav><div className="cg-sidebar-foot">{DEMO_MODE&&<label>Demo role switcher<select value={role} onChange={e=>{switchRole(e.target.value);navigate(`/${e.target.value}/dashboard`)}}><option value="ambulance">Ambulance</option><option value="nurse">Nurse</option><option value="doctor">Doctor</option></select></label>}<button onClick={signOut}><SignOut/> Sign out</button></div></aside><div className="cg-workspace"><header className="cg-topbar"><div><b>{titles[role]}</b><span>{location.pathname.split("/").filter(Boolean).slice(1).join(" / ").replaceAll("-"," ")||"dashboard"}</span></div><button className="cg-live-status" onClick={()=>setSystemOpen(true)}><span className={`cg-live-dot ${connection}`}/><div><b>Gateway {connectionLabel[connection]}</b><small>Ward 01 {live.device?.connectionStatus||"OFFLINE"}{live.lastUpdated?` · ${new Date(live.lastUpdated).toLocaleTimeString()}`:""}</small></div><CaretDown/></button><div className="cg-user"><span>{session?.name?.split(" ").map(x=>x[0]).join("").slice(0,2)||"CG"}</span><div><b>{session?.name}</b><small>{titles[role]}</small></div></div></header><PanicBanner/><div className="cg-route-view"><Outlet/></div></div><SystemStatusDrawer/></div>
}
