import test from "node:test";
import assert from "node:assert/strict";
import { adaptHospitalEnvelope, adaptHospitalWard, extractHospitalWard, moduleStatus } from "../src/adapters/hospitalWardAdapter.js";

const data={uptime_ms:9000,vitals:{valid:true,heart_rate:78,spo2:98},environment:{lux:193.3,temperature_c:27.3,pressure_hpa:967.8,pm1:40,pm25:52,pm10:64},bin:{valid:true,distance_cm:46.5,fill_percent:0,full:false},bed:{vibration:false,status:"stable"},emergency:{panic:false,status:"NORMAL"},air:{adc:3431,gpio_voltage:2.8,sensor_voltage:4.2,baseline_ready:true,anomaly:false},rfid:{last_uid:"D0:DA:F6:5F"},health:{wifi:true,wifi_rssi:-19,mqtt:true,bh1750:true,max30100:true,bmp180:true,oled:true,pms5003:true,ultrasonic:true,rc522:true,mq:true,vibration:true,panic_button:true}};
const envelope={nodes:{hospital_ward_01:{device_id:"hospital_ward_01",node_type:"smart_hospital_ward",online:true,last_seen:"2026-08-25T10:00:00+05:30",data}}};

test("extracts nodes.hospital_ward_01.data and preserves node metadata",()=>{const raw=extractHospitalWard(envelope);assert.equal(raw.device_id,"hospital_ward_01");assert.equal(raw.node_type,"smart_hospital_ward");assert.equal(raw._receivedAt,"2026-08-25T10:00:00+05:30")});
test("maps all new hospital readings without inventing values",()=>{const model=adaptHospitalEnvelope(envelope);assert.equal(model.vitals.heartRate.display,"78 bpm");assert.equal(model.vitals.spo2.display,"98%");assert.equal(model.environment.temperature.display,"27.3 °C");assert.equal(model.environment.pressure.display,"967.8 hPa");assert.equal(model.environment.lux.display,"193.3 lux");assert.equal(model.rfid.lastUid,"D0:DA:F6:5F");assert.equal(model.air.anomaly,false);assert.equal(model.bed.status,"stable")});
test("MAX30100 online without a valid finger shows Waiting for patient",()=>{const model=adaptHospitalWard({...data,vitals:{valid:false,heart_rate:0,spo2:0}});assert.equal(model.vitals.heartRate.available,false);assert.equal(model.vitals.heartRate.value,null);assert.equal(model.vitals.heartRate.display,"Waiting for patient");assert.equal(model.vitals.spo2.display,"Waiting for patient");assert.equal(model.vitals.waitingForPatient,true)});
test("MAX30100 fault shows Sensor Offline rather than zero",()=>{const model=adaptHospitalWard({...data,vitals:{valid:false,heart_rate:0,spo2:0},health:{...data.health,max30100:false}});assert.equal(model.vitals.heartRate.display,"Sensor Offline");assert.equal(model.vitals.waitingForPatient,false)});
test("PMS5003 offline or null values remain unavailable",()=>{const offline=adaptHospitalWard({...data,health:{...data.health,pms5003:false}}),missing=adaptHospitalWard({...data,environment:{...data.environment,pm25:null}});assert.equal(offline.environment.pm1.display,"Sensor Offline");assert.equal(offline.environment.pm25.value,null);assert.equal(missing.environment.pm25.display,"Sensor Offline")});
test("panic, vibration and RFID states map directly",()=>{const model=adaptHospitalWard({...data,bed:{vibration:true,status:"movement"},emergency:{panic:true,status:"PANIC"}});assert.equal(model.emergency.panic,true);assert.equal(model.bed.vibration,true);assert.equal(model.rfid.lastUid,"D0:DA:F6:5F")});
test("central health list reports online and failed modules",()=>{const model=adaptHospitalWard({...data,health:{...data.health,mqtt:false,pms5003:false}}),statuses=moduleStatus(model);assert.equal(statuses.find(x=>x.key==="mqtt").severity,"critical");assert.equal(statuses.find(x=>x.key==="pms5003").severity,"unavailable");assert.equal(statuses.find(x=>x.key==="max30100").ok,true)});
test("Raspberry Pi day-first timestamps are normalized for immediate REST rendering",()=>{const model=adaptHospitalEnvelope({nodes:{hospital_ward_01:{last_seen:"25-08-2026 11.04.54 AM",data}}});assert.equal(Number.isNaN(new Date(model.updatedAt).getTime()),false)});
