import { caregridRequest } from "./caregridApi.js";

const normalizeCase = item => {
  const source = item?.case || item || {};
  const patientContext = source.patient_context || {};
  return { ...source, id: source.id, caseNumber: source.case_number, patient: source.patient_name || patientContext.name || source.patient || "Unknown patient", name: source.patient_name || patientContext.name || source.patient || "Unknown patient", patientId: source.patient_id || patientContext.patient_id, rfid: source.rfid_uid || patientContext.rfid_uid, type: source.category || source.incident_type, category: source.category || source.incident_type, department: source.department_required || source.requested_department || "Emergency", bed: source.bed_type_required || source.requested_bed || "Emergency", bedType: source.bed_type_required || source.requested_bed || "Emergency", medicine: source.medicine_required, equipment: source.equipment_required || [], hospitalId: source.selected_hospital_id || source.hospital_id, destination: source.selected_hospital_name || source.destination, eta: source.eta_minutes, vitals: { heartRate: source.heart_rate ?? null, spo2: source.spo2 ?? null }, preAlert: item?.prealert || source.prealert || null };
};
export async function getAmbulances() { const response = await caregridRequest("/api/emergency-cases"); return (response.items || []).map(normalizeCase); }
export async function getEmergencyCase(id) { return normalizeCase(await caregridRequest(`/api/emergency-cases/${encodeURIComponent(id)}`)); }
export async function createEmergency(input) { const payload = input.incident ? input : { incident: { category: input.category, severity: input.severity, notes: input.notes }, patient: { patient_id: input.patientId, name: input.name, age: input.age, gender: input.gender, rfid_uid: input.rfid }, vitals: { heart_rate: input.heartRate ?? null, spo2: input.spo2 ?? null }, requirements: { department: input.department, bed_type: input.bedType, medicine: input.medicine, equipment: input.equipment || [] }, location: input.location, source: "ambulance_operator" }; return normalizeCase(await caregridRequest("/api/emergency-cases", { method: "POST", body: JSON.stringify(payload) })); }
export async function recommendEmergencyCase(id) { return caregridRequest(`/api/emergency-cases/${encodeURIComponent(id)}/recommend`); }
export async function confirmEmergencyDestination(id, hospitalId) { const response = await caregridRequest(`/api/emergency-cases/${encodeURIComponent(id)}/confirm-destination`, { method: "POST", body: JSON.stringify({ hospital_id: hospitalId }) }); return { ...response, case: normalizeCase(response.case) }; }
export async function updateEmergency(id, input) { return normalizeCase(await caregridRequest(`/api/emergency-cases/${encodeURIComponent(id)}`, { method: "PATCH", body: JSON.stringify(input) })); }
export async function sendHospitalPreAlert(input) { return caregridRequest("/api/prealerts", { method: "POST", body: JSON.stringify({ ...input, caseId: input.caseId || input.ambulanceId }) }); }
export async function getPreAlerts(filters = {}) { const params = new URLSearchParams(Object.entries(filters).filter(([, value]) => value)); const response = await caregridRequest(`/api/prealerts${params.toString() ? `?${params}` : ""}`); return response.items || []; }
export async function getPreAlert(id) { return caregridRequest(`/api/prealerts/${encodeURIComponent(id)}`); }
export async function acknowledgePreAlert(id, acknowledgedBy) { return caregridRequest(`/api/prealerts/${encodeURIComponent(id)}/acknowledge`, { method: "POST", body: JSON.stringify({ acknowledged_by: acknowledgedBy }) }); }
export async function markAmbulanceArrived(id) { return normalizeCase(await caregridRequest(`/api/emergency-cases/${encodeURIComponent(id)}/arrive`, { method: "POST" })); }
export async function closeEmergency(id) { return normalizeCase(await caregridRequest(`/api/emergency-cases/${encodeURIComponent(id)}/close`, { method: "POST" })); }
