import { ArrowClockwise, Broadcast, Cpu, WifiHigh, X } from "@phosphor-icons/react";
import { moduleStatus } from "../../adapters/hospitalWardAdapter.js";
import { useCareGrid } from "../../app/providers.jsx";
import { Badge, Button, formatUptime } from "./ui.jsx";

const labels={live:"LIVE",reconnecting:"RECONNECTING",offline:"OFFLINE",loading:"RECONNECTING"};
export function SystemStatusDrawer(){
  const {live,refresh,systemOpen,setSystemOpen}=useCareGrid();if(!systemOpen)return null;const device=live.device,state=live.connectionState||"offline";
  return <div className="cg-drawer-backdrop" onMouseDown={()=>setSystemOpen(false)}><aside className="cg-drawer" onMouseDown={e=>e.stopPropagation()}><header><div><span>System status</span><h2>CareGrid Network</h2></div><button aria-label="Close status drawer" onClick={()=>setSystemOpen(false)}><X/></button></header><div className="cg-system-summary"><span className={`cg-live-dot ${state}`}/><div><b>Gateway {labels[state]}</b><small>{live.lastUpdated?`Last telemetry ${new Date(live.lastUpdated).toLocaleTimeString()}`:"No hospital telemetry received"}</small></div><Badge tone={state==="live"?"healthy":state==="reconnecting"?"warning":"critical"}>{labels[state]}</Badge></div><div className="cg-status-facts"><div><Broadcast/><span>Physical Ward 01<b>{device?.connectionStatus||"OFFLINE"} {device?.ageSeconds!=null?`· ${device.ageSeconds}s`:""}</b></span></div><div><Cpu/><span>Realtime WebSocket<b>{state==="live"?"Connected":state==="reconnecting"?`Retry ${live.reconnectAttempt||1}`:"Offline"}</b></span></div><div><WifiHigh/><span>Wi-Fi RSSI (last reported)<b>{device?.connectivity.wifiRssi!=null?`${device.connectivity.wifiRssi} dBm`:"Unavailable"}</b></span></div><div><Cpu/><span>Node uptime<b>{device?.uptimeMs?formatUptime(device.uptimeMs):"Unavailable"}</b></span></div></div><h3>Sensor health</h3><div className="cg-module-list">{device?moduleStatus(device).map(item=><div key={item.key}><span className={`cg-module-dot ${item.severity}`}/><b>{item.label}</b><Badge tone={item.severity}>{item.ok?"Online":"Offline"}</Badge></div>):<p>No device telemetry.</p>}</div>{live.transport==="legacy-rest"&&<p className="cg-inline-warning">The Pi is serving real ward data through the legacy REST endpoint. Deploy `/api/hospital/latest` and `/ws/hospital` to enable native realtime delivery.</p>}{live.error&&<p className="cg-inline-warning">{live.error}</p>}<Button icon={ArrowClockwise} onClick={()=>refresh()}>Reconnect / Refresh</Button></aside></div>
}
