import { ArrowClockwise, Broadcast, Drop, Gauge, Heartbeat, IdentificationCard, Pulse, Thermometer, Trash, Warning, WaveSine, WifiHigh, Wind } from "@phosphor-icons/react";
import { useEffect, useState } from "react";
import { useCareGrid } from "../../app/providers.jsx";
import { moduleStatus } from "../../adapters/hospitalWardAdapter.js";
import { Badge, Button, Card, PageHeader } from "../../components/common/ui.jsx";
import { resolveRfidUid } from "../../services/rfidService.js";

const stateLabel={live:"LIVE",reconnecting:"RECONNECTING",offline:"OFFLINE",loading:"RECONNECTING"};
const toneForState={live:"healthy",reconnecting:"warning",offline:"critical",loading:"warning"};
const unavailable=text=><span className="cg-sensor-unavailable">{text||"Unavailable"}</span>;

function ReadingCard({icon:Icon,label,reading,waiting}){return <article className="cg-reading-card"><span><Icon weight="duotone"/></span><div><small>{label}</small><strong>{reading?.available?reading.display:"--"}</strong><em>{reading?.available?"Realtime ward reading":waiting?"Waiting for patient":reading?.display||"Sensor Offline"}</em></div></article>}
function Value({label,value,tone="info",offline="Unavailable"}){return <div><span>{label}</span>{value===null||value===undefined?unavailable(offline):<Badge tone={tone}>{String(value)}</Badge>}</div>}

export default function RealtimeDashboard(){
  const {live,refresh}=useCareGrid(),d=live.device,state=live.connectionState||live.status;
  const [rfidIdentity,setRfidIdentity]=useState(null);
  useEffect(()=>{let active=true;const uid=d?.rfid.lastUid;if(!uid){setRfidIdentity(null);return()=>{active=false}}resolveRfidUid(uid).then(result=>{if(active)setRfidIdentity(result)}).catch(()=>{if(active)setRfidIdentity({known:false,status:"Unknown RFID Tag",uid})});return()=>{active=false}},[d?.rfid.lastUid]);
  return <><PageHeader title="Smart ward command" subtitle="Realtime hospital_ward_01 telemetry through the Raspberry Pi CareGrid Gateway." actions={<><Badge tone={toneForState[state]}>{stateLabel[state]}</Badge><Button icon={ArrowClockwise} onClick={()=>refresh()}>Reconnect / Refresh</Button></>}/>
  {!d&&<section className="cg-live-empty"><Broadcast/><h2>{state==="offline"?"CareGrid Gateway Offline":"Connecting to hospital_ward_01"}</h2><p>{live.error||"Waiting for the initial hospital state."}</p><Button icon={ArrowClockwise} onClick={()=>refresh()}>Retry connection</Button></section>}
  {d&&<><div className="cg-realtime-strip"><span className={`cg-live-dot ${state}`}/><b>Gateway {stateLabel[state]}</b><span>{d.id} · {d.nodeType}</span><span>Last telemetry {new Date(d.updatedAt).toLocaleTimeString()} · {d.ageSeconds??"--"}s</span><span>{live.transport==="legacy-rest"?"Real Pi data · legacy REST compatibility":"Raspberry Pi REST + WebSocket"}</span><Badge tone={d.connectionStatus==="LIVE"?"healthy":d.connectionStatus==="STALE"?"warning":"critical"}>Ward {d.connectionStatus}</Badge></div>
  <div className="cg-reading-grid"><ReadingCard icon={Heartbeat} label="Heart rate" reading={d.vitals.heartRate} waiting={d.vitals.waitingForPatient}/><ReadingCard icon={Drop} label="SpO₂" reading={d.vitals.spo2} waiting={d.vitals.waitingForPatient}/><ReadingCard icon={Thermometer} label="Temperature" reading={d.environment.temperature}/><ReadingCard icon={Gauge} label="Atmospheric pressure" reading={d.environment.pressure}/></div>
  {d.vitals.waitingForPatient&&<div className="cg-patient-waiting"><Pulse/><div><b>Waiting for patient</b><span>MAX30100 is online, but no valid finger reading is available.</span></div></div>}
  <div className="cg-dashboard-grid cg-realtime-grid"><Card title="Ward environment"><div className="cg-status-rows"><Value label="Light level" value={d.environment.lux.available?d.environment.lux.display:null} offline="Sensor Offline"/><Value label="PM1" value={d.environment.pm1.available?d.environment.pm1.display:null} offline="Sensor Offline"/><Value label="PM2.5" value={d.environment.pm25.available?d.environment.pm25.display:null} offline="Sensor Offline"/><Value label="PM10" value={d.environment.pm10.available?d.environment.pm10.display:null} offline="Sensor Offline"/></div></Card>
  <Card title="Medical waste bin"><div className="cg-bin"><Trash weight="duotone"/><strong>{d.bin.available?`${d.bin.fillPercent}%`:"--"}</strong><span>{d.bin.available?`${d.bin.distanceCm} cm from sensor`:"Ultrasonic sensor offline"}</span><div><i style={{width:`${d.bin.available?d.bin.fillPercent:0}%`}}/></div><Badge tone={!d.bin.available?"unavailable":d.bin.full?"critical":d.bin.fillPercent>=75?"warning":"healthy"}>{!d.bin.available?"Sensor Offline":d.bin.full?"Bin Full":"Within Capacity"}</Badge></div></Card>
  <Card title="Bed & safety"><div className="cg-safety-state"><WaveSine/><strong>{d.bed.vibration===null?"Sensor Offline":d.bed.vibration?"Vibration Detected":"Stable"}</strong><span>Bed vibration · {d.bed.status}</span></div><div className="cg-status-rows"><Value label="Panic button" value={d.emergency.available?(d.emergency.panic?"PANIC ACTIVE":d.emergency.status):null} tone={d.emergency.panic?"critical":"healthy"} offline="Sensor Offline"/><Value label="Vibration sensor" value={d.bed.vibration===null?null:(d.bed.vibration?"Triggered":"Stable")} tone={d.bed.vibration?"warning":"healthy"} offline="Sensor Offline"/></div></Card>
  <Card title="MQ air / vapor"><div className={`cg-air-state ${d.air.anomaly?"danger":""}`}><Wind/><strong>{!d.air.available?"Sensor Offline":d.air.anomaly?"Anomaly Detected":"Normal"}</strong><span>{d.air.baselineReady?"Baseline ready":"Calibrating baseline"}</span></div><div className="cg-status-rows"><Value label="ADC" value={d.air.adc}/><Value label="GPIO voltage" value={d.air.gpioVoltage!==null?`${d.air.gpioVoltage} V`:null}/><Value label="Sensor voltage" value={d.air.sensorVoltage!==null?`${d.air.sensorVoltage} V`:null}/></div></Card>
  <Card title="Latest RFID scan"><div className="cg-rfid-live"><IdentificationCard weight="duotone"/><strong>{rfidIdentity?.known?`${rfidIdentity.entity?.name} · ${rfidIdentity.entity_id}`:d.rfid.available?(d.rfid.lastUid||"Waiting for RFID"):"Sensor Offline"}</strong><span>{rfidIdentity?.known?`${rfidIdentity.status} · ${rfidIdentity.uid}`:d.rfid.lastUid?(rfidIdentity?.status||"Resolving RFID identity…"):"No card UID received"}</span></div></Card>
  <Card title="Node connectivity"><div className="cg-status-rows"><Value label="Wi-Fi" value={d.connectivity.wifi?"Connected":"Offline"} tone={d.connectivity.wifi?"healthy":"critical"}/><Value label="Wi-Fi RSSI" value={d.connectivity.wifiRssi!==null?`${d.connectivity.wifiRssi} dBm`:null}/><Value label="MQTT" value={d.connectivity.mqtt?"Connected":"Disconnected"} tone={d.connectivity.mqtt?"healthy":"critical"}/><Value label="Realtime channel" value={stateLabel[state]} tone={toneForState[state]}/></div></Card></div>
  <div className="cg-two-col wide-left"><Card title="Individual sensor health"><div className="cg-sensor-health-grid">{moduleStatus(d).map(item=><div key={item.key}><span className={`cg-module-dot ${item.severity}`}/><span><b>{item.label}</b><small>{item.ok?"Online / Connected":"Offline / Fault"}</small></span><Badge tone={item.severity}>{item.ok?"Online":"Offline"}</Badge></div>)}</div></Card><Card title="Emergency & activity log"><ActivityLog entries={live.events}/></Card></div></>}</>}

function ActivityLog({entries}){if(!entries.length)return <div className="cg-empty"><Warning/>No realtime ward events received</div>;return <div className="cg-activity-log">{entries.slice(0,12).map(item=><article key={item.id} className={item.severity}><span/><div><b>{item.message}</b><small>{item.source} · {new Date(item.timestamp).toLocaleTimeString()}</small></div></article>)}</div>}
